### ISSUE TITLE
Copyleft license?

### ISSUE THREAD

**Issue by jacobsvante** [easybe/smart-garden-gateway-mqtt-client#10]
Why did you decide on a copyleft license?

**Comment by easybe** [comment]
Why not use a copyleft license? Does it limit you in any way?

**Comment by jacobsvante** [comment]
> Why not use a copyleft license?

Because it might put unnecessary restrictions on how the software can be used.

> Does it limit you in any way?

Not me personally, no.

I think it's good to state why a project chooses a copyleft license over a more permissive license like MIT or Apache.

**Comment by easybe** [comment]
As this software can only really be used on the GARDENA smart Gateway, we do not see the need to allow modifying/extending it without giving back/publishing the changes. Should there ever be an actual need to change the license, we can revisit the topic.

**Comment by jacobsvante** [comment]
Okay, thanks for your response.
